# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "plum"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = [
  "Clemens Koza <https://github.com/SillyFreak/>"
]
license = "MIT"
description = "Create UML class diagrams in Typst; inspired by but *not* compatible with PlantUML"
# homepage = ""
repository = "https://github.com/SillyFreak/typst-plum"
keywords = ["software", "uml", "class-diagram"]
categories = ["visualization"]
disciplines = ["computer-science"]
# compiler = ""
exclude = [
  ".github",
  "docs",
  "gallery",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
